all:
    children:
        eks_nodes:
            hosts:
                192.168.1.20:
                    ansible_ssh_user: ec2-user
                    ansible_ssh_private_key_file: ~/.ssh/id_rsa
            vars:
                ansible_python_interpreter: /usr/bin/python3
                aws_region: us-east-1
                eks_cluster_name: eks-cluster
