- name: Run All Playbooks Sequentially
  hosts: localhost
  gather_facts: no
  become: true
  strategy: free
  tasks:
    - name: Run the first playbook (terraform.yml)
      import_playbook: playbooks/terraform.yml

    - name: Run the second playbook (ecr_login.yml)
      import_playbook: playbooks/ecr_login.yml

    - name: Run the third playbook (docker_build.yml)
      import_playbook: playbooks/docker_build.yml

    - name: Run the third playbook (deploy_eks.yml)
      import_playbook: playbooks/deploy_eks.yml
